config/routes.rb
Rails.application.routes.draw do
  root "links#index"
  match '/submit', to: 'static#submit', via: [:get, :post]
  match '/about', to: 'static#about', via: [:get, :post]
  
  resources :comments
  as :user do
  get "/signin" => "devise/sessions#new"
  get "/signout" => "devise/sessions#destroy"
  get "/signup" => "devise/registrations#new"
  get "/account" => "devise/registrations#edit"
  end

  devise_for :users
  resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :user
  belongs_to :link
  
end

app/models/link.rb
class Link < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def new
  end
  
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @link, notice: 'Comment was successfully created.'
    else
      redirect_to @link, notice: 'Comment was empty.'
    end
  end
    
    
  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to @link, notice: 'Comment was successfully created.' }
  #       format.json { render json: @comment, status: :created, location: @comment }
  #     else
  #       render @link
  #       format.html { render action: "new" }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order('created_at DESC').page(params[:page]).per(15)
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
      if current_user.admin?
        @link = current_user.links.build
      else
        redirect_to root_path
      end
  end
  

  # GET /links/1/edit
  def edit
    if current_user.admin?
    end
  end

  # POST /links
  # POST /links.json
  def create
    if current_user.admin?
      @link = current_user.links.build(link_params)

      respond_to do |format|
        if @link.save
          format.html { redirect_to @link, notice: 'Link was successfully created.' }
          format.json { render :show, status: :created, location: @link }
        else
          format.html { render :new }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
        end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_from current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def authorized_user
      @link = current_user.links.find_by(id: params[:id])
      redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def submit
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.name %></small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user %>
				<%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br>
    <%= f.number_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--//Code sanitized to protect the foolish.-->
<!--using System;-->
<!--using System.Collections.Generic;-->
<!--using System.Text;-->
<!--using System.Reflection;-->
<!--using System.Web.UI;-->

<!--namespace Mobile.Web.Control-->
<!--{-->
<!--    /// <summary>-->
<!--    /// Class used to work around Richard being a fucking idiot-->
<!--    /// </summary>-->
<!--    /// <remarks>-->
<!--    /// The point of this is to work around his poor design so that paging will -->
<!--    /// work on a mobile control. The main problem is the BindCompany() method, -->
<!--    /// which he hoped would be able to do everything. I hope he dies.-->
<!--    /// </remarks>-->
<!--    public abstract class RichardIsAFuckingIdiotControl : MobileBaseControl, ICompanyProfileControl-->
<!--    {-->
<!--        protected abstract Pager Pager { get; }-->

<!--        public void BindCompany(int companyId) { }-->

<!--        public RichardIsAFuckingIdiotControl()-->
<!--        {-->
<!--            MakeSureNobodyAccidentallyGetsBittenByRichardsStupidity();-->
<!--        }-->

<!--        private void MakeSureNobodyAccidentallyGetsBittenByRichardsStupidity()-->
<!--        {-->
<!--            // Make sure nobody is actually using that fucking bindcompany method-->
<!--            MethodInfo m = this.GetType().GetMethod("BindCompany", BindingFlags.DeclaredOnly | -->
<!--                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);-->
<!--            if (m != null)-->
<!--//Code sanitized to protect the foolish.-->
<!--using System;-->
<!--using System.Collections.Generic;-->
<!--using System.Text;-->
<!--using System.Reflection;-->
<!--using System.Web.UI;-->

<!--namespace Mobile.Web.Control-->
<!--{-->
<!--    /// <summary>-->
<!--    /// Class used to work around Richard being a fucking idiot-->
<!--    /// </summary>-->
<!--    /// <remarks>-->
<!--    /// The point of this is to work around his poor design so that paging will -->
<!--    /// work on a mobile control. The main problem is the BindCompany() method, -->
<!--    /// which he hoped would be able to do everything. I hope he dies.-->
<!--    /// </remarks>-->
<!--    public abstract class RichardIsAFuckingIdiotControl : MobileBaseControl, ICompanyProfileControl-->
<!--    {-->
<!--        protected abstract Pager Pager { get; }-->

<!--        public void BindCompany(int companyId) { }-->

<!--        public RichardIsAFuckingIdiotControl()-->
<!--        {-->
<!--            MakeSureNobodyAccidentallyGetsBittenByRichardsStupidity();-->
<!--        }-->

<!--        private void MakeSureNobodyAccidentallyGetsBittenByRichardsStupidity()-->
<!--        {-->
<!--            // Make sure nobody is actually using that fucking bindcompany method-->
<!--            MethodInfo m = this.GetType().GetMethod("BindCompany", BindingFlags.DeclaredOnly | -->
<!--                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);-->
<!--            if (m != null)--><!--//Code sanitized to protect the foolish.-->
<!--using System;-->
<!--using System.Collections.Generic;-->
<!--using System.Text;-->
<!--using System.Reflection;-->
<!--using System.Web.UI;-->

<!--namespace Mobile.Web.Control-->
<!--{-->
<!--    /// <summary>-->
<!--    /// Class used to work around Richard being a fucking idiot-->
<!--    /// </summary>-->
<!--    /// <remarks>-->
<!--    /// The point of this is to work around his poor design so that paging will -->
<!--    /// work on a mobile control. The main problem is the BindCompany() method, -->
<!--    /// which he hoped would be able to do everything. I hope he dies.-->
<!--    /// </remarks>-->
<!--    public abstract class RichardIsAFuckingIdiotControl : MobileBaseControl, ICompanyProfileControl-->
<!--    {-->
<!--        protected abstract Pager Pager { get; }-->

<!--        public void BindCompany(int companyId) { }-->

<!--        public RichardIsAFuckingIdiotControl()-->
<!--        {-->
<!--            MakeSureNobodyAccidentallyGetsBittenByRichardsStupidity();-->
<!--        }-->

<!--        private void MakeSureNobodyAccidentallyGetsBittenByRichardsStupidity()-->
<!--        {-->
<!--            // Make sure nobody is actually using that fucking bindcompany method-->
<!--            MethodInfo m = this.GetType().GetMethod("BindCompany", BindingFlags.DeclaredOnly | -->
<!--                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);-->
<!--            if (m != null)-->


<!-- WHY ON EARTH ARE YOU READING MY CODE, BITCH-->
<html>
<head>
  <title>IITR Confessions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favic.png' %>
</head>
<body>
	<header class="navbar navbar-default navbar-fixed-top navbar" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "IITR Confessions", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'Submit Post', '/submit' %></li>
						<!--<li><%# link_to 'About', '/about' %></li>-->
						<% if user_signed_in? -%>
							<% if current_user.admin? -%>
								<li><%= link_to 'Post link', new_link_path %></li>
							<% end %>
							<li><%= link_to 'Account', '/account' %></li>
							<li><%= link_to 'Sign out', '/signout' %></li>
						</ul>
					<% else -%>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to 'Sign up', '/signup' %></li>
							<li><%= link_to 'Sign in', '/signin' %></li>
						</ul>
					<% end -%>
        </nav>
      </div>
    </div>
  </header>

	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
        <ul>
        <% @link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= f.label :Post %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <br>
    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h3>
      <%= link.title %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago by Admin</small>
    </h3>

    <div class="btn-group">
      <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Downvote
        <%= link.get_downvotes.size %>
      <% end %>
      <%= link_to link, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-comment"></span>
        Comment
      <% end %>
    </div>
  </div>
<% end %>
<%= paginate@links, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered" %>

app/views/links/new.html.erb
<% if current_user.admin? %>
    <h1>Submit New Post</h1>
    <%= render 'form' %>
    <%= link_to 'Back', links_path %>
<% end %>

app/views/links/show.html.erb
<div class="page-header">
  <h3><%= @link.title %><br> <small>Submitted by Admin</small></h3>
  <small class="author"> <%= time_ago_in_words(@link.created_at) %> ago</small>
</div>

<div class="btn-group pull-right">
  <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    Upvote
    <%= @link.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down">
    Downvote
    <%= @link.get_downvotes.size %>
  <% end %>
</div>

<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
		<%= link_to 'Delete', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
	</div>
<% end %>

<h3 class="comments_title">
  <%= @link.comments.count %> Comments
</h3>

<div id="comments">
  <%= render :partial => @link.comments %>
</div>
<%= simple_form_for [@link, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>